#!/bin/sh

# clean times
foamListTimes -rm
foamListTimes -rm -processor
rm -r processor*

# clean logs
rm log.*

# remove xml logs
rm *.xml

#------------------------------------------------------------------------------
